package ga.rugal.jpt.core.dao;

import ga.rugal.jpt.core.entity.Invitation;
import ga.rugal.jpt.core.entity.User;
import java.util.List;
import ml.rugal.sshcommon.hibernate.Updater;
import ml.rugal.sshcommon.page.Pagination;

/**
 *
 * @author Rugal Bernstein
 */
public interface InvitationDao
{

    Invitation updateByUpdater(Updater<Invitation> updater);

    Invitation delete(Invitation bean);

    Invitation save(Invitation bean);

    Pagination getPage(int pageNo, int pageSize);

    Invitation get(String id);

    /**
     * Check if the given invitation code is valid and available.<BR>
     * Valid: this invitation code is generated by the given invitor.<BR>
     * Available: this invitation code haven't been consumed by anyone else since creation.
     *
     * @param invitor The user who generate this invitation code
     * @param id
     *
     * @return
     */
    boolean isUsable(User invitor, String id);

    /**
     * Get a list of usable invitation code of a specific user.
     *
     * @param invitor
     *
     * @return
     */
    List<String> getUsableCode(User invitor);
}
